parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
    useJSXTextNode: true
  ecmaVersion: 2018
  sourceType: module
  project:
    - ./tsconfig.json
    - ./packages/*/tsconfig.json
#  tsconfigRootDir: .
#  extraFileExtensions:
#    - mdx


extends:
  - 'eslint:recommended'
  - 'plugin:react-hooks/recommended'
  - 'plugin:react/recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:prettier/recommended'
#  - 'plugin:mdx/recommended'

globals:
  Atomics: readonly
  SharedArrayBuffer: readonly

rules:
  no-unused-vars: 'off'
  linebreak-style: 'off'
  react/react-in-jsx-scope: off
  react/jsx-curly-brace-presence:
    - 'error'
    - props: 'never'
      children: 'never'
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: warn
  react/prop-types: off
  prettier/prettier:
    - error
    - endOfLine: auto
  '@typescript-eslint/ban-ts-comment': off
  '@typescript-eslint/no-empty-interface':
    - error
    - allowSingleExtends: true



overrides:
  - files:
    - '*.mdx'
    extends: 'plugin:mdx/recommended'


plugins:
  - react
  - react-hooks
  - '@typescript-eslint'
  - prettier

env:
  browser: true
  jasmine: true
  jest: true
  es6: true

settings:
  react:
    pragma: React
    version: detect
  mdx:
    code-blocks: true
